var http = require('http');
var formidable = require('formidable');
const express = require('express')
var fs = require('fs');
var IVRMenu = require('./IVRMenu.js')
var ExcelReader = require('./ExcelReader.js')
var XMLWriter = require('./XMLWriter')
var XMLReader = require('./XMLReader')
var AuditWriter = require('./AuditWriter')
var path = require("path");
var LucidChartReader = require('./LucidChartReader')
const PrettyAuditWriter = require('./PrettyAuditWriter')

const PORT = process.env.PORT || 3000

const app = express();

app.listen(PORT, () => {
  console.log(`Server listening on ${PORT}`);
})

app.use(express.static(path.resolve(__dirname, '../frontend/build')))

app.post('/fileupload', (req: any, res: any) => {
  var form = new formidable.IncomingForm({multiples: true});
        
        form.parse(req, function (err: any, fields: any, files: any) {

            var filePath = files.filetoupload.filepath;

            if (files.filetoupload.originalFilename.includes('.xlsx')) {
              
              // This is an excel file, process accordingly
              let resultingFilename = files.filetoupload.originalFilename.replace(".xlsx", ".xml")
              const reader = new ExcelReader(filePath)
              let menus = reader.getMenus()
              let xmlWriter = new XMLWriter(menus)

              res.setHeader('Content-Length', xmlWriter.xmlData.length);
              res.setHeader('Content-Type', 'text/xml');
              res.setHeader('Content-Disposition', 'attachment; filename=' + resultingFilename);
              res.write(xmlWriter.xmlData, 'binary');
              res.end()
            }
            else if (files.filetoupload.originalFilename.includes('.xml')) {
              // This is an XML file, generate audit
              let resultingFilename = files.filetoupload.originalFilename.replace(".xml", ".csv")
              let xmlReader = new XMLReader(filePath)
              let menus = xmlReader.getMenus()
              let auditWriter = new AuditWriter(menus)

              res.setHeader('Content-Length', auditWriter.csvData.length);
              res.setHeader('Content-Type', 'text/xml');
              res.setHeader('Content-Disposition', 'attachment; filename=' + resultingFilename);
              res.write(auditWriter.csvData, 'binary');
              res.end()
            }
            else if (files.filetoupload.originalFilename.includes('.csv')) {
              // This is a CSV file. Assume it was generated by LucidChart
              
              let pages: any[] = [] // An array containing Lucidchart page names

              if (fields.page instanceof Array) {
                pages = fields.page
              }
              else {
                pages.push(fields.page)
              }

              let reader = new LucidChartReader(files.filetoupload.filepath)
              reader.getMenus().then((menus: any) => {
                // Filter out menus from pages not selected by the user
                const filteredMenus = menus.filter((menu: any) => {
                  for (let index = 0; index < pages.length; index++) {
                    if (menu.page == pages[index]) {
                      return true
                    }
                  }
                  return false
                })

                let xmlWriter = new XMLWriter(filteredMenus)
                let outputFilename = files.filetoupload.originalFilename.replace(".csv", ".xml")

                res.setHeader('Content-Length', xmlWriter.xmlData.length);
                res.setHeader('Content-Type', 'text/xml');
                res.setHeader('Content-Disposition', 'attachment; filename=' + outputFilename);
                res.write(xmlWriter.xmlData, 'binary');
                res.end()
              })
            }
     });
})

app.post('/audit', (req: any, res: any) => {
  var form = new formidable.IncomingForm();

        form.parse(req, function (err: any, fields: any, files: any) {

          var filePath = files.filetoupload.filepath;
          let resultingFilename = files.filetoupload.originalFilename.replace(".xml", ".xlsx")
          let xmlReader = new XMLReader(filePath)
          let menus = xmlReader.getMenus()

          const prettyAuditWriter = new PrettyAuditWriter(menus)
          prettyAuditWriter.getData().then((data: any) => {
            res.setHeader('Content-Length', data.length);
            res.setHeader('Content-Type', 'application/vnd.ms-excel  ');
            res.setHeader('Content-Disposition', 'attachment; filename=' + resultingFilename);
            res.write(data, 'binary');
            res.end()
          })
        
        });
})

app.get('*', (req: any, res: any) => {
  res.sendFile(path.resolve(__dirname, '../frontend/build', 'index.html'));
})
